---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: source run
      shell: source ~/anaconda3/etc/profile.d/conda.sh executable=/bin/bash

#    - name: Activate Conda environment
#      shell: ". ~/anaconda3/bin/activate mltosca"
#
#    - name: Run Python script
#      shell: python KeepColumns.py Name,Age /home/artjom/Downloads/df.pkl
