---
- name: Activate Conda environment and run Python script
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Activate Conda environment
      shell: ". ~/anaconda3/bin/activate mltosca && python ReadCSV.py {{project_location}} {{filepath}} {{delimiter}} {{encoding}} &"

      # // TODO: check if file exists and throw error
