---
- name: Activate Conda environment and run Python script
  hosts: all
  gather_facts: yes

  tasks:
    - name: Check if input is a URL
      uri:
        url: "{{ filepath }}"
        method: HEAD
      register: url_response
      ignore_errors: yes
      when: filepath is match('^(http|https)://') and filepath is ends_with('.csv')

    - name: Check if input is a local file
      stat:
        path: "{{ filepath }}"
      register: file_response
      when: filepath is not match('^(http|https)://')

    - name: Throw an error if input is invalid
      fail:
        msg: "Invalid input provided"
      when: url_response.status is not defined and not file_response.stat.exists

    - name: Create folder
      file:
        path: "{{ project_location }}/{{output_folder}}"
        state: directory

    - name: Copy files to external VM
      synchronize:
        src: ReadFile.py
        dest: "{{ ansible_env.HOME }}/ReadFile.py"

    - name: Activate Conda environment
      shell: ". ~/anaconda3/bin/activate mltosca && nohup ~/anaconda3/envs/mltosca/bin/python ReadFile.py {{project_location}}/{{output_folder}} {{filepath}} {{parameters}} &"

    - name: Remove file
      file:
        path: "{{ ansible_env.HOME }}/ReadFile.py"
        state: absent
