---
- name: Evaluation
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create folder
      file:
        path: "{{ project_location }}/{{output_folder}}"
        state: directory

    - name: Activate Conda environment
      shell: ". ~/anaconda3/bin/activate mltosca && python script.py {{project_location}} {{output_folder}} &"
