---
- name: Write execution count to file
  hosts: localhost

  tasks:
    - name: Create my_folder directory
      file:
        path: "{{ project_location }}/evaluation"
        state: directory

    - name: Check if file exists
      stat:
        path: "{{ project_location }}/evaluation/metrics.txt"
      register: file_info

    - name: Append input to file
      copy:
        dest: "{{ project_location }}/evaluation/metrics.txt"
        content: |
          {% if file_info.stat.exists %}
          {{ lookup('file', '{{ project_location }}/evaluation/metrics.txt') }}
          {% endif %}
          {{ function_id }}
