---
- name: Evaluation
  hosts: all
  gather_facts: yes

  tasks:
    - name: Create folder
      file:
        path: "{{export_folder}}"
        state: directory

    - name: Copy files to external VM
      synchronize:
        src: script.py
        dest: "{{ ansible_env.HOME }}/script.py"

    - name: Activate Conda environment
      shell: "nohup ~/anaconda3/envs/mltosca/bin/python script.py {{project_location}} {{output_folder}} {{export_folder}} &"

    - name: Remove file
      file:
        path: "{{ ansible_env.HOME }}/script.py"
        state: absent
