---
- name: Activate Conda environment and run Python script
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create folder
      file:
        path: "{{ project_location }}/{{output_folder}}"
        state: directory

    - name: Activate Conda environment
      shell: ". ~/anaconda3/bin/activate mltosca && python split.py {{project_location}}/{{output_folder}} {{project_location}}/{{previous_output_folder}} {{test_size}} &"
